// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jstytygxbnapydwkvpzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzdHl0eWd4Ym5hcHlkd2t2cHprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNjMwMTAsImV4cCI6MjA3MjkzOTAxMH0.UyfFJPxdImFrKccGpMq-OZLUK60bs6DbqiN886ExPuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});